/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rebuildingui;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jtrader17
 */
public class EditSponsorsUI extends javax.swing.JFrame {

    private DefaultTableModel dm = new DefaultTableModel();
    private InitialUI in;
    private File myFile = new File("C:\\Users\\jTrader17\\Documents\\GitHub\\InternetApps\\Rebuiding\\Rebuilding Together Spokane\\Sponsors.html");
    
    /**
     * Creates new form EditSponsorsUI
     */
    public EditSponsorsUI(InitialUI in) {
        initComponents();
        this.setVisible(false);
        sponsorTable.setModel(dm);
        dm.addColumn("Sponsors");
        this.in = in;
        this.addWindowListener(exit);
        init();
    }
    
    WindowListener exit = new WindowAdapter(){
        @Override
        /**
         * @param e
         * sets previous window to visible
         */
        public void windowClosing(WindowEvent e){
            in.setVisible(true);
        }
    };
    
    public void init(){
        dm.setRowCount(0);
        try{
            BufferedReader rdr = new BufferedReader(new FileReader(myFile));
            String line;
            while ((line = rdr.readLine()) != null){
                Pattern p = Pattern.compile("src=\"pics/sponsors/(.*)?[.]");
                Matcher m = p.matcher(line);
                while(m.find()){
                    dm.addRow(new Object[] {m.group(1)});
                }
            }
            rdr.close();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sponsorTable = new javax.swing.JTable();
        addRadio = new javax.swing.JRadioButton();
        dropRadio = new javax.swing.JRadioButton();
        error = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Current Sponsors");

        sponsorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(sponsorTable);

        addRadio.setText("Add Sponsor");
        addRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadioActionPerformed(evt);
            }
        });

        dropRadio.setText("Drop Sponsor");
        dropRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRadioActionPerformed(evt);
            }
        });

        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropRadio)
                    .addComponent(addRadio)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadioActionPerformed
        dropRadio.setSelected(false);
    }//GEN-LAST:event_addRadioActionPerformed

    private void dropRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRadioActionPerformed
        addRadio.setSelected(false);
    }//GEN-LAST:event_dropRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        error.setText("");
        if(dropRadio.isSelected())
            drop();
        if(addRadio.isSelected());
            add();
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void drop(){
        int num = sponsorTable.getSelectedRow();
        File temp = new File("temp.txt") ; 
        if (num == -1){
            error.setText("Please select a row.");
        }
        else{
            String s = dm.getValueAt(num, 0).toString();
            String myNew;
            String myPatt = "<li><a target=\"_blank\" href=(.*)><img class=\"sponsor-pics\" src=\"pics/sponsors/" + s + ".(.*)\"></a>?</img></li>";
            try{
                BufferedReader rdr = new BufferedReader(new FileReader(myFile));
                BufferedWriter wrtr = new BufferedWriter(new FileWriter(temp));
                String line;
                while ((line = rdr.readLine()) != null){
                    myNew=line;
                    Pattern p = Pattern.compile(myPatt);
                    Matcher m = p.matcher(line);
                    while (m.find()){
                        myNew=m.replaceAll("");
                    }
                    if (!myNew.isEmpty()){
                        write(wrtr, myNew);    
                    }   
                }
                wrtr.close();
                rdr.close();
            }
            catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            init();
        }
        
    }
    
    private void write(BufferedWriter wrtr, String line){
        try{
            wrtr.write(line);
            wrtr.newLine();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void add(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSponsorsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSponsorsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSponsorsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSponsorsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSponsorsUI(new InitialUI()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addRadio;
    private javax.swing.JRadioButton dropRadio;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sponsorTable;
    // End of variables declaration//GEN-END:variables
}
